version: '3'
services:
  mockserver:
    build: .
    environment:
      ADDR: "0.0.0.0:8080"
      CONFIG_PATH: /examples/simple_driver.yaml
    volumes:
      - ./examples/:/examples/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080/healthcheck"]
    ports:
      - 8080:8080
    networks:
      - mock
networks:
  mock: